// Generated by https://quicktype.io

export interface RegisterBody {
  fullName: string;
  dni: string;
  email: string;
  password: string;
  phone: string;
  address: string;
  latitude: string;
  longitude: string;
  city: string;
  department: string;
  roles: Roles[];
}

export enum Roles {
  user = "user",
  employee = "employee",
  admin = "admin",
  superadmin = "superadmin",
}
